// Converts plain-text markdown-style headings/quotes into HTML when a story
// is pasted into the editor. TipTap's built-in heading shortcuts ("### " +
// space) only trigger while *typing* live — pasting a whole pre-written
// story (very common workflow: written elsewhere, or generated by an AI
// assistant, then pasted here) skips that input-rule entirely, so "###
// Capítulo 1" was landing as literal text instead of a heading. This runs
// only when the clipboard has no real text/html payload (see handlePaste in
// RichTextEditor.tsx) — genuine rich pastes (Word, Google Docs) are left to
// TipTap's normal HTML-paste handling.

function escapeHtml(text: string): string {
	return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function inlineMarkdownToHtml(text: string): string {
	let html = escapeHtml(text);
	html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
	html = html.replace(/(?<!\*)\*([^*]+?)\*(?!\*)/g, '<em>$1</em>');
	return html;
}

/** True when the pasted text actually looks like it uses markdown headings/quotes — avoids mangling ordinary prose that just happens to contain a "#" or ">" character. */
export function looksLikeMarkdown(text: string): boolean {
	return /(^|\n)#{1,6}\s+\S|(^|\n)>\s+\S/.test(text);
}

export function markdownTextToHtml(text: string): string {
	const lines = text.replace(/\r\n?/g, '\n').split('\n');
	const htmlParts: string[] = [];
	let paragraphLines: string[] = [];

	function flushParagraph() {
		if (paragraphLines.length > 0) {
			htmlParts.push(`<p>${paragraphLines.map(inlineMarkdownToHtml).join('<br>')}</p>`);
			paragraphLines = [];
		}
	}

	for (const rawLine of lines) {
		const line = rawLine.trim();
		if (line === '') {
			flushParagraph();
			continue;
		}

		const headingMatch = /^(#{1,6})\s+(.*)$/.exec(line);
		if (headingMatch) {
			flushParagraph();
			const level = Math.min(headingMatch[1].length, 3); // matches the levels StarterKit's heading extension renders
			htmlParts.push(`<h${level}>${inlineMarkdownToHtml(headingMatch[2])}</h${level}>`);
			continue;
		}

		const quoteMatch = /^>\s+(.*)$/.exec(line);
		if (quoteMatch) {
			flushParagraph();
			htmlParts.push(`<blockquote><p>${inlineMarkdownToHtml(quoteMatch[1])}</p></blockquote>`);
			continue;
		}

		paragraphLines.push(line);
	}
	flushParagraph();

	return htmlParts.join('');
}
